# config for docker
global:
  scrape_interval:     5s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # Evaluate rules every 15 seconds.

  # Attach these extra labels to all timeseries collected by this Prometheus instance.
  external_labels:
    monitor: 'codelab-monitor'

rule_files:
  - "/conf/*.rules"

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["192.168.0.66:9100","localhost:9090"]
        labels:
          device_ID: "local"
  - job_name: "25"
    static_configs:
      - targets: ["192.168.1.25:10250"]
        labels:
          device_ID: "25"
  - job_name: "docker"
    static_configs:
      - targets: ['localhost:9323']

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "192.168.0.66:9093"



