# export CURRENT_GOPATH=$HOME/go
# export CODIES_DIR=$CURRENT_GOPATH/src/codies-server
codies-server:
  image: golang:1.7.5-alpine
  working_dir: /go/src/codies-server
  command: go run cmd/livereload/main.go -watch=server -o=server -e=vendor,Godeps,docker,cmd
  volumes:
    - $CODIES_DIR:/go/src/codies-server
  ports:
    - 8888:8888
  links:
    - redis
    - mysql

redis:
  image: redis:3.2-alpine
  ports:
    - 6377:6379

mysql:
  image: mysql:5.7.17
  command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  volumes:
    - $CODIES_DIR/docker/volumes/mysql:/var/lib/mysql
  ports:
    - 3307:3306
  environment:
    MYSQL_ROOT_PASSWORD: codies-pwd